/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7;

import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.tree.*;

/**
 *
 * @author jason
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Creacion = new javax.swing.JDialog();
        rb_Usuario = new javax.swing.JRadioButton();
        rb_Artista = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_Crear = new javax.swing.JButton();
        pf_Contraseña1 = new javax.swing.JPasswordField();
        jd_Nacimiento = new com.toedter.calendar.JDateChooser();
        tf_Apellido = new javax.swing.JTextField();
        tf_Nombre = new javax.swing.JTextField();
        jl_Usuario1 = new javax.swing.JLabel();
        tf_Usuario1 = new javax.swing.JTextField();
        jd_Usuario = new javax.swing.JDialog();
        jl_Titulo_C = new javax.swing.JLabel();
        tf_Agregar_LC = new javax.swing.JButton();
        tf_Cancion1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        JL_Canciones = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        JL_Artistas = new javax.swing.JList<>();
        jl_Lista_A = new javax.swing.JLabel();
        jl_Lista_C = new javax.swing.JLabel();
        jl_Titulo_C1 = new javax.swing.JLabel();
        bt_Playlist = new javax.swing.JButton();
        tf_Playlist_N = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jl_GP = new javax.swing.JLabel();
        tf_GP = new javax.swing.JTextField();
        jd_GP = new com.toedter.calendar.JDateChooser();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_PlayLists = new javax.swing.JTree();
        jl_Lista_A1 = new javax.swing.JLabel();
        bt_Agregar_PL = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_Agregar_PL = new javax.swing.JTextField();
        pb_Cancion = new javax.swing.JProgressBar();
        bt_Play = new javax.swing.JButton();
        jd_Artista = new javax.swing.JDialog();
        jl_Titulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jl_Duracion = new javax.swing.JLabel();
        bt_Crear1 = new javax.swing.JButton();
        tf_Cancion = new javax.swing.JTextField();
        jd_Creacion_C = new com.toedter.calendar.JDateChooser();
        tf_Duracion = new javax.swing.JTextField();
        jl_Canciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Canciones_A = new javax.swing.JList<>();
        br_Crear2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jd_Creacion_Al = new com.toedter.calendar.JDateChooser();
        jl_Albumes = new javax.swing.JLabel();
        tf_Album = new javax.swing.JTextField();
        jl_Titulo2 = new javax.swing.JLabel();
        bt_Agregar_AL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Albumes = new javax.swing.JTree();
        jLabel5 = new javax.swing.JLabel();
        tf_Agregar_AL1 = new javax.swing.JTextField();
        jl_Seguidore = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_Seguidores = new javax.swing.JList<>();
        jl_Login = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        tf_Usuario = new javax.swing.JTextField();
        pf_Contraseña = new javax.swing.JPasswordField();
        bt_Login = new javax.swing.JButton();
        bt_Crear_U = new javax.swing.JButton();
        bt_Crear_A = new javax.swing.JButton();

        jd_Creacion.setTitle("Creacion de Usuarios");

        rb_Usuario.setText("Usuario");

        rb_Artista.setText("Artista");

        jLabel1.setText("Nombre ");

        jLabel2.setText("Apellido");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Fecha de Nacimiento");

        bt_Crear.setText("Crear");
        bt_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearActionPerformed(evt);
            }
        });

        jl_Usuario1.setText("Usuario");

        javax.swing.GroupLayout jd_CreacionLayout = new javax.swing.GroupLayout(jd_Creacion.getContentPane());
        jd_Creacion.getContentPane().setLayout(jd_CreacionLayout);
        jd_CreacionLayout.setHorizontalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CreacionLayout.createSequentialGroup()
                        .addComponent(rb_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Artista))
                    .addComponent(bt_Crear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CreacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CreacionLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(pf_Contraseña1))
                        .addGroup(jd_CreacionLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_Apellido))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CreacionLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jd_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CreacionLayout.createSequentialGroup()
                        .addComponent(jl_Usuario1)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 152, Short.MAX_VALUE))
        );
        jd_CreacionLayout.setVerticalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_Contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario1)
                    .addComponent(tf_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jd_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_Usuario)
                    .addComponent(rb_Artista))
                .addGap(18, 18, 18)
                .addComponent(bt_Crear)
                .addGap(26, 26, 26))
        );

        jd_Usuario.setTitle("Interfaz de Usuario");

        jl_Titulo_C.setText("Titulo de la Cancion");

        tf_Agregar_LC.setText("Agregar a Lista de Canciones y Artistas");
        tf_Agregar_LC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_Agregar_LCActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(JL_Canciones);

        jScrollPane5.setViewportView(JL_Artistas);

        jl_Lista_A.setText("Lista de Artistas");

        jl_Lista_C.setText("Lista de Canciones");

        jl_Titulo_C1.setText("Titulo de la Playliist");

        bt_Playlist.setText("Crear PlayList");
        bt_Playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PlaylistActionPerformed(evt);
            }
        });

        jLabel8.setText("Genero de la Playlist");

        jl_GP.setText("Fecha de Creacion de la Playlist");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("PlayLists");
        jt_PlayLists.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane6.setViewportView(jt_PlayLists);

        jl_Lista_A1.setText("Lista de PlayList");

        bt_Agregar_PL.setText("Agregar a PlayList");
        bt_Agregar_PL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Agregar_PLActionPerformed(evt);
            }
        });

        jLabel9.setText("Ingrese el nomrbe de la Playlist");

        bt_Play.setText("Play Cancion");
        bt_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_UsuarioLayout = new javax.swing.GroupLayout(jd_Usuario.getContentPane());
        jd_Usuario.getContentPane().setLayout(jd_UsuarioLayout);
        jd_UsuarioLayout.setHorizontalGroup(
            jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioLayout.createSequentialGroup()
                        .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_UsuarioLayout.createSequentialGroup()
                                        .addComponent(jl_Titulo_C)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_Cancion1))
                                    .addComponent(jScrollPane4))
                                .addGap(18, 18, 18))
                            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                                .addComponent(jl_Lista_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(164, 164, 164)))
                        .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(pb_Cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5)
                                .addComponent(jl_Lista_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6)
                            .addComponent(jl_Lista_A1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                        .addGap(286, 286, 286))
                    .addGroup(jd_UsuarioLayout.createSequentialGroup()
                        .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Playlist)
                            .addComponent(tf_Agregar_LC)
                            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                                .addComponent(jl_Titulo_C1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_Playlist_N, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_GP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                                .addComponent(jl_GP, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jd_GP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Agregar_PL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_Agregar_PL))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_UsuarioLayout.createSequentialGroup()
                        .addComponent(bt_Play)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jd_UsuarioLayout.setVerticalGroup(
            jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Titulo_C)
                    .addComponent(tf_Cancion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_Cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Agregar_LC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Titulo_C1)
                    .addComponent(tf_Playlist_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_GP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_GP)
                    .addComponent(jd_GP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(bt_Playlist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Lista_C)
                    .addComponent(jl_Lista_A)
                    .addComponent(jl_Lista_A1))
                .addGap(6, 6, 6)
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane5))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_Agregar_PL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_Agregar_PL)
                .addGap(52, 52, 52)
                .addComponent(bt_Play)
                .addGap(35, 35, 35))
        );

        jd_Artista.setTitle("Interfaz de Artista");

        jl_Titulo.setText("Titulo de la Cancion");

        jLabel6.setText("Año de Publicacion");

        jl_Duracion.setText("Duracion");

        bt_Crear1.setText("Crear Cancion");
        bt_Crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear1ActionPerformed(evt);
            }
        });

        jl_Canciones.setText("Canciones Creadas");

        jScrollPane1.setViewportView(JL_Canciones_A);

        br_Crear2.setText("Crear Album");
        br_Crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_Crear2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Año de Publicacion");

        jl_Albumes.setText("Albumes Creados");

        jl_Titulo2.setText("Titulo del Album");

        bt_Agregar_AL.setText("Agregar a Abum");
        bt_Agregar_AL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Agregar_ALActionPerformed(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        jt_Albumes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_Albumes);

        jLabel5.setText("Ingrese nombre del Album a Agregar");

        jl_Seguidore.setText("Lista de Seguidores");

        jScrollPane3.setViewportView(JL_Seguidores);

        javax.swing.GroupLayout jd_ArtistaLayout = new javax.swing.GroupLayout(jd_Artista.getContentPane());
        jd_Artista.getContentPane().setLayout(jd_ArtistaLayout);
        jd_ArtistaLayout.setHorizontalGroup(
            jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ArtistaLayout.createSequentialGroup()
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(jl_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Cancion))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(jl_Duracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Duracion))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jd_Creacion_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_Crear1)
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Titulo2)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Album))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jd_Creacion_Al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(br_Crear2)
                    .addComponent(jl_Seguidore)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(123, 123, 123)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl_Albumes)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addComponent(jl_Canciones))
                .addGap(18, 18, 18)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_Agregar_AL1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(bt_Agregar_AL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_ArtistaLayout.setVerticalGroup(
            jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Titulo)
                    .addComponent(tf_Cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Canciones)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jd_Creacion_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl_Duracion)
                                .addComponent(tf_Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(bt_Crear1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(tf_Agregar_AL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Agregar_AL)))
                .addGap(33, 33, 33)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Albumes)
                    .addComponent(tf_Album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Titulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jd_Creacion_Al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(br_Crear2)
                        .addGap(39, 39, 39)
                        .addComponent(jl_Seguidore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(108, 108, 108))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leotify");

        jl_Login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_Login.setText("Log In");

        jl_Contraseña.setText("Contraseña");

        jl_Usuario.setText("Usuario");

        bt_Login.setText("Login");
        bt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LoginActionPerformed(evt);
            }
        });

        bt_Crear_U.setText("Crear Usuario");

        bt_Crear_A.setText("Crear Artista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_Contraseña)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_Login)
                                .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_Usuario)
                            .addGap(18, 18, 18)
                            .addComponent(pf_Contraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Login)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Crear_U)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Crear_A)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jl_Login)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Contraseña))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Usuario))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Login)
                    .addComponent(bt_Crear_U)
                    .addComponent(bt_Crear_A))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LoginActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < persona.size(); i++) {
            if (tf_Usuario.getText().equals(((Usuario) persona.get(i)).getUsuario()) && pf_Contraseña.getText().equals(((Usuario) persona.get(i)).getContraseña())) {
                jd_Usuario.setModal(true);
                jd_Usuario.pack();
                jd_Usuario.setLocationRelativeTo(this);
                jd_Usuario.setVisible(true);
                break;
            } else if (tf_Usuario.getText().equals(((Artista) persona.get(i)).getUsuario()) && pf_Contraseña.getText().equals(((Artista) persona.get(i)).getContraseña())) {
                jd_Artista.setModal(true);
                jd_Artista.pack();
                jd_Artista.setLocationRelativeTo(this);
                jd_Artista.setVisible(true);
                break;
            } else {
                JOptionPane.showMessageDialog(this, "Usuario incorrecto o no existe");
                break;
            }
        }//Fin del for que recorre la lista de persona
        tf_Usuario.setText("");
        pf_Contraseña.setText("");
    }//GEN-LAST:event_bt_LoginActionPerformed

    private void bt_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearActionPerformed
        // TODO add your handling code here:
        if (rb_Usuario.isSelected() == true) {
            u = new Usuario(tf_Usuario1.getText(), tf_Nombre.getText(), tf_Apellido.getText(), pf_Contraseña1.getText(), jd_Nacimiento.getDate());
            adminPersona ap = new adminPersona("./Usuario");
            persona.add(u);
            ap.cargarArchivo();
            ap.setPersona(u);
            ap.escribirArchivo();
        } else if (rb_Artista.isSelected() == true) {
            a = new Artista(tf_Usuario1.getText(), tf_Nombre.getText(), tf_Apellido.getText(), pf_Contraseña1.getText(), jd_Nacimiento.getDate());
            adminPersona ap = new adminPersona("./Artista");
            persona.add(a);
            ap.cargarArchivo();
            ap.setPersona(a);
            ap.escribirArchivo();
        } else if (rb_Artista.isSelected() == false && rb_Usuario.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar usuario o artista");
        }
        tf_Usuario1.setText("");
        tf_Nombre.setText("");
        tf_Apellido.setText("");
        pf_Contraseña1.setText("");
        jd_Nacimiento.setDate(new Date());
    }//GEN-LAST:event_bt_CrearActionPerformed

    private void bt_Crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear1ActionPerformed
        // TODO add your handling code here:
        c = new Cancion(tf_Cancion.getText(), jd_Creacion_C.getDate(), a.getNombre(), Integer.parseInt(tf_Duracion.getText()));
        a.setCancion(c);
        adminPersona ap = new adminPersona("./Artista");
        a.setCancion(c);
        ap.cargarArchivo();
        ap.setPersona(a);
        ap.escribirArchivo();
        duracion += c.getDuracion();
        ca.add(c);
        DefaultListModel modelo = (DefaultListModel) JL_Canciones_A.getModel();
        modelo.addElement(c.getNombre());
        tf_Cancion.setText("");
        tf_Duracion.setText("");
        jd_Creacion_C.setDate(new Date());
    }//GEN-LAST:event_bt_Crear1ActionPerformed

    private void br_Crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_Crear2ActionPerformed
        // TODO add your handling code here:
        al = new Album(tf_Album.getText(), jd_Creacion_Al.getDate(), a.getNombre());
        adminPersona ap = new adminPersona("./Artistas");
        a.setAlbum(al);
        ap.cargarArchivo();
        ap.setPersona(a);
        ap.escribirArchivo();
        tf_Album.setText("");
        jd_Creacion_Al.setDate(new Date());
    }//GEN-LAST:event_br_Crear2ActionPerformed

    private void bt_Agregar_ALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Agregar_ALActionPerformed
        // TODO add your handling code here:
        if (tf_Agregar_AL1.getText().equals(al.getNombre())) {
            DefaultTreeModel m = (DefaultTreeModel) jt_Albumes.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_album;
            nodo_album = new DefaultMutableTreeNode(al.getNombre());
            DefaultMutableTreeNode año;
            año = new DefaultMutableTreeNode(new SimpleDateFormat("YYYY").format(c.getAño()));
            DefaultMutableTreeNode cancion = new DefaultMutableTreeNode(c);
            año.add(cancion);
            raiz.add(nodo_album);
            m.reload();
        } else {
            JOptionPane.showMessageDialog(this, "El nombre del album no existe");
        }
    }//GEN-LAST:event_bt_Agregar_ALActionPerformed

    private void tf_Agregar_LCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_Agregar_LCActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < ca.size(); i++) {
            if (((Cancion) ca.get(i)).getNombre().equals(tf_Cancion1.getText())) {
                DefaultListModel modelo = (DefaultListModel) JL_Canciones.getModel();
                modelo.addElement(c.getNombre());
                DefaultListModel modelo1 = (DefaultListModel) JL_Artistas.getModel();
                modelo1.addElement(c.getNombre_A());
                DefaultListModel modelo2 = (DefaultListModel) JL_Seguidores.getModel();
                modelo1.addElement(u.getNombre());
                u.setCancion(c);
                adminPersona ap = new adminPersona("./Usuario");
                ap.cargarArchivo();
                ap.setPersona(u);
                ap.escribirArchivo();
                tf_Cancion1.setText("");
                break;
            } else {
                JOptionPane.showConfirmDialog(this, "El titulo de la Cancion no Existe");
            }
        }
    }//GEN-LAST:event_tf_Agregar_LCActionPerformed

    private void bt_PlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PlaylistActionPerformed
        // TODO add your handling code here
        pl = new Playlist(tf_Playlist_N.getText(), tf_GP.getText(), jd_GP.getDate(), duracion);
        u.setPlaylist(pl);
        adminPersona ap = new adminPersona("./Usuario");
        ap.cargarArchivo();
        ap.setPersona(u);
        ap.escribirArchivo();
        tf_Playlist_N.setText("");
        tf_GP.setText("");
    }//GEN-LAST:event_bt_PlaylistActionPerformed

    private void bt_Agregar_PLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Agregar_PLActionPerformed
        // TODO add your handling code here:
        if (tf_Agregar_PL.getText().equals(pl.getNombre())) {
            DefaultTreeModel m = (DefaultTreeModel) jt_PlayLists.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nod_playlist;
            nod_playlist = new DefaultMutableTreeNode(pl.getNombre());
            DefaultMutableTreeNode año;
            año = new DefaultMutableTreeNode(new SimpleDateFormat("YYYY").format(c.getAño()));
            DefaultMutableTreeNode cancion = new DefaultMutableTreeNode(c);
            año.add(cancion);
            raiz.add(nod_playlist);
            m.reload();
        } else {
            JOptionPane.showMessageDialog(this, "El nombre del album no existe");
        }
    }//GEN-LAST:event_bt_Agregar_PLActionPerformed

    private void bt_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PlayActionPerformed
        // TODO add your handling code here:
        if (JL_Canciones.getSelectedIndex() >= 0) {

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una cancion antes de darle play");
        }
    }//GEN-LAST:event_bt_PlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JL_Artistas;
    private javax.swing.JList<String> JL_Canciones;
    private javax.swing.JList<String> JL_Canciones_A;
    private javax.swing.JList<String> JL_Seguidores;
    private javax.swing.JButton br_Crear2;
    private javax.swing.JButton bt_Agregar_AL;
    private javax.swing.JButton bt_Agregar_PL;
    private javax.swing.JButton bt_Crear;
    private javax.swing.JButton bt_Crear1;
    private javax.swing.JButton bt_Crear_A;
    private javax.swing.JButton bt_Crear_U;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Play;
    private javax.swing.JButton bt_Playlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDialog jd_Artista;
    private javax.swing.JDialog jd_Creacion;
    private com.toedter.calendar.JDateChooser jd_Creacion_Al;
    private com.toedter.calendar.JDateChooser jd_Creacion_C;
    private com.toedter.calendar.JDateChooser jd_GP;
    private com.toedter.calendar.JDateChooser jd_Nacimiento;
    private javax.swing.JDialog jd_Usuario;
    private javax.swing.JLabel jl_Albumes;
    private javax.swing.JLabel jl_Canciones;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Duracion;
    private javax.swing.JLabel jl_GP;
    private javax.swing.JLabel jl_Lista_A;
    private javax.swing.JLabel jl_Lista_A1;
    private javax.swing.JLabel jl_Lista_C;
    private javax.swing.JLabel jl_Login;
    private javax.swing.JLabel jl_Seguidore;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JLabel jl_Titulo2;
    private javax.swing.JLabel jl_Titulo_C;
    private javax.swing.JLabel jl_Titulo_C1;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JLabel jl_Usuario1;
    private javax.swing.JTree jt_Albumes;
    private javax.swing.JTree jt_PlayLists;
    private javax.swing.JProgressBar pb_Cancion;
    private javax.swing.JPasswordField pf_Contraseña;
    private javax.swing.JPasswordField pf_Contraseña1;
    private javax.swing.JRadioButton rb_Artista;
    private javax.swing.JRadioButton rb_Usuario;
    private javax.swing.JTextField tf_Agregar_AL1;
    private javax.swing.JButton tf_Agregar_LC;
    private javax.swing.JTextField tf_Agregar_PL;
    private javax.swing.JTextField tf_Album;
    private javax.swing.JTextField tf_Apellido;
    private javax.swing.JTextField tf_Cancion;
    private javax.swing.JTextField tf_Cancion1;
    private javax.swing.JTextField tf_Duracion;
    private javax.swing.JTextField tf_GP;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Playlist_N;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JTextField tf_Usuario1;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Persona> persona = new ArrayList();
    private ArrayList<Cancion> ca = new ArrayList();
    private Usuario u;
    private Artista a;
    private Cancion c;
    private Playlist pl;
    private Album al;
    private int duracion = 0;
}
