/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7;

import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.tree.*;

/**
 *
 * @author jason
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Creacion = new javax.swing.JDialog();
        rb_Usuario = new javax.swing.JRadioButton();
        rb_Artista = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_Crear = new javax.swing.JButton();
        pf_Contraseña1 = new javax.swing.JPasswordField();
        jd_Nacimiento = new com.toedter.calendar.JDateChooser();
        tf_Apellido = new javax.swing.JTextField();
        tf_Nombre = new javax.swing.JTextField();
        jl_Usuario1 = new javax.swing.JLabel();
        tf_Usuario1 = new javax.swing.JTextField();
        jd_Usuario = new javax.swing.JDialog();
        jd_Artista = new javax.swing.JDialog();
        jl_Titulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jl_Duracion = new javax.swing.JLabel();
        bt_Crear1 = new javax.swing.JButton();
        tf_Cancion = new javax.swing.JTextField();
        jd_Creacion_C = new com.toedter.calendar.JDateChooser();
        tf_Duracion = new javax.swing.JTextField();
        jl_Canciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Canciones_A = new javax.swing.JList<>();
        br_Crear2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jd_Creacion_Al = new com.toedter.calendar.JDateChooser();
        jl_Albumes = new javax.swing.JLabel();
        tf_Album = new javax.swing.JTextField();
        jl_Titulo2 = new javax.swing.JLabel();
        bt_Agregar_AL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Albumes = new javax.swing.JTree();
        jLabel5 = new javax.swing.JLabel();
        tf_Agregar_AL1 = new javax.swing.JTextField();
        jl_Login = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        tf_Usuario = new javax.swing.JTextField();
        pf_Contraseña = new javax.swing.JPasswordField();
        bt_Login = new javax.swing.JButton();
        bt_Crear_U = new javax.swing.JButton();
        bt_Crear_A = new javax.swing.JButton();

        rb_Usuario.setText("Usuario");

        rb_Artista.setText("Artista");

        jLabel1.setText("Nombre ");

        jLabel2.setText("Apellido");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Fecha de Nacimiento");

        bt_Crear.setText("Crear");
        bt_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearActionPerformed(evt);
            }
        });

        jl_Usuario1.setText("Usuario");

        javax.swing.GroupLayout jd_CreacionLayout = new javax.swing.GroupLayout(jd_Creacion.getContentPane());
        jd_Creacion.getContentPane().setLayout(jd_CreacionLayout);
        jd_CreacionLayout.setHorizontalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CreacionLayout.createSequentialGroup()
                        .addComponent(rb_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Artista))
                    .addComponent(bt_Crear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CreacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CreacionLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(pf_Contraseña1))
                        .addGroup(jd_CreacionLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_Apellido))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CreacionLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jd_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CreacionLayout.createSequentialGroup()
                        .addComponent(jl_Usuario1)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 152, Short.MAX_VALUE))
        );
        jd_CreacionLayout.setVerticalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_Contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario1)
                    .addComponent(tf_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jd_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_Usuario)
                    .addComponent(rb_Artista))
                .addGap(18, 18, 18)
                .addComponent(bt_Crear)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jd_UsuarioLayout = new javax.swing.GroupLayout(jd_Usuario.getContentPane());
        jd_Usuario.getContentPane().setLayout(jd_UsuarioLayout);
        jd_UsuarioLayout.setHorizontalGroup(
            jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_UsuarioLayout.setVerticalGroup(
            jd_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jl_Titulo.setText("Titulo de la Cancion");

        jLabel6.setText("Año de Publicacion");

        jl_Duracion.setText("Duracion");

        bt_Crear1.setText("Crear Cancion");
        bt_Crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear1ActionPerformed(evt);
            }
        });

        jl_Canciones.setText("Canciones Creadas");

        jScrollPane1.setViewportView(JL_Canciones_A);

        br_Crear2.setText("Crear Album");
        br_Crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_Crear2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Año de Publicacion");

        jl_Albumes.setText("Albumes Creados");

        jl_Titulo2.setText("Titulo del Album");

        bt_Agregar_AL.setText("Agregar a Abum");
        bt_Agregar_AL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Agregar_ALActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        jt_Albumes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_Albumes);

        jLabel5.setText("Ingrese nombre del Album a Agregar");

        javax.swing.GroupLayout jd_ArtistaLayout = new javax.swing.GroupLayout(jd_Artista.getContentPane());
        jd_Artista.getContentPane().setLayout(jd_ArtistaLayout);
        jd_ArtistaLayout.setHorizontalGroup(
            jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ArtistaLayout.createSequentialGroup()
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addComponent(jl_Titulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_Cancion))
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addComponent(jl_Duracion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_Duracion))
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jd_Creacion_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_Crear1)
                    .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jl_Titulo2)
                            .addGap(18, 18, 18)
                            .addComponent(tf_Album))
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jd_Creacion_Al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(br_Crear2))
                .addGap(123, 123, 123)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl_Albumes)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addComponent(jl_Canciones))
                .addGap(18, 18, 18)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(bt_Agregar_AL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_Agregar_AL1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jd_ArtistaLayout.setVerticalGroup(
            jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Titulo)
                    .addComponent(tf_Cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Canciones)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_ArtistaLayout.createSequentialGroup()
                            .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jd_Creacion_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl_Duracion)
                                .addComponent(tf_Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(bt_Crear1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addComponent(tf_Agregar_AL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Agregar_AL)))
                .addGap(18, 18, 18)
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Albumes)
                    .addComponent(tf_Album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Titulo2))
                .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArtistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jd_Creacion_Al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(br_Crear2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ArtistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_Login.setText("Log In");

        jl_Contraseña.setText("Contraseña");

        jl_Usuario.setText("Usuario");

        bt_Login.setText("Login");
        bt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LoginActionPerformed(evt);
            }
        });

        bt_Crear_U.setText("Crear Usuario");

        bt_Crear_A.setText("Crear Artista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_Contraseña)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_Login)
                                .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_Usuario)
                            .addGap(18, 18, 18)
                            .addComponent(pf_Contraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Login)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Crear_U)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Crear_A)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jl_Login)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Contraseña))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Usuario))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Login)
                    .addComponent(bt_Crear_U)
                    .addComponent(bt_Crear_A))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LoginActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < persona.size(); i++) {
            if (tf_Usuario.getText().equals(((Usuario) persona.get(i)).getUsuario()) && pf_Contraseña.getText().equals(((Usuario) persona.get(i)).getContraseña())) {
                jd_Usuario.setModal(true);
                jd_Usuario.pack();
                jd_Usuario.setLocationRelativeTo(this);
                jd_Usuario.setVisible(true);
            } else if (tf_Usuario.getText().equals(((Artista) persona.get(i)).getUsuario()) && pf_Contraseña.getText().equals(((Artista) persona.get(i)).getContraseña())) {
                jd_Artista.setModal(true);
                jd_Artista.pack();
                jd_Artista.setLocationRelativeTo(this);
                jd_Artista.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario incorrecto o no existe");
                break;
            }
        }//Fin del for que recorre la lista de persona
        tf_Usuario.setText("");
        pf_Contraseña.setText("");
    }//GEN-LAST:event_bt_LoginActionPerformed

    private void bt_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearActionPerformed
        // TODO add your handling code here:
        if (rb_Usuario.isSelected() == true) {
            u = new Usuario(tf_Usuario1.getText(), tf_Nombre.getText(), tf_Apellido.getText(), pf_Contraseña1.getText(), jd_Nacimiento.getDate());
            adminPersona ap = new adminPersona("./Usuario");
            persona.add(u);
            ap.cargarArchivo();
            ap.setPersona(a);
            ap.escribirArchivo();
        } else if (rb_Artista.isSelected() == true) {
            a = new Artista(tf_Usuario1.getText(), tf_Nombre.getText(), tf_Apellido.getText(), pf_Contraseña1.getText(), jd_Nacimiento.getDate());
            adminPersona ap = new adminPersona("./Artista");
            persona.add(a);
            ap.cargarArchivo();
            ap.setPersona(a);
            ap.escribirArchivo();
        } else if (rb_Artista.isSelected() == false && rb_Usuario.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar usuario o artista");
        }
        tf_Usuario1.setText("");
        tf_Nombre.setText("");
        tf_Apellido.setText("");
        pf_Contraseña1.setText("");
        jd_Nacimiento.setDate(new Date());
    }//GEN-LAST:event_bt_CrearActionPerformed

    private void bt_Crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear1ActionPerformed
        // TODO add your handling code here:
        c = new Cancion(tf_Cancion.getText(), jd_Creacion_C.getDate(), a.getNombre(), Integer.parseInt(tf_Duracion.getText()));
        al = new Album(tf_Album.getText(), jd_Creacion_Al.getDate(), a.getNombre());
        a.setAlbum(al);
        a.setCancion(c);
        DefaultListModel modelo = (DefaultListModel) JL_Canciones_A.getModel();
        modelo.addElement(c);
        tf_Album.setText("");
        jd_Creacion_Al.setDate(new Date());
        tf_Cancion.setText("");
        tf_Duracion.setText("");
        jd_Creacion_C.setDate(new Date());
    }//GEN-LAST:event_bt_Crear1ActionPerformed

    private void br_Crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_Crear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br_Crear2ActionPerformed

    private void bt_Agregar_ALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Agregar_ALActionPerformed
        // TODO add your handling code here:
        if (tf_Agregar_AL1.getText().equals(al.getNombre())) {
            DefaultTreeModel m = (DefaultTreeModel) jt_Albumes.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_album;
            nodo_album = new DefaultMutableTreeNode(al.getNombre());
            DefaultMutableTreeNode año;
            año = new DefaultMutableTreeNode(new SimpleDateFormat("YYYY").format(new Date()));
            DefaultMutableTreeNode cancion = new DefaultMutableTreeNode(c);
            año.add(cancion);
            raiz.add(nodo_album);
            m.reload();
        } else {
            JOptionPane.showMessageDialog(this, "El nombre del album no existe");
        }
    }//GEN-LAST:event_bt_Agregar_ALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JL_Canciones_A;
    private javax.swing.JButton br_Crear2;
    private javax.swing.JButton bt_Agregar_AL;
    private javax.swing.JButton bt_Crear;
    private javax.swing.JButton bt_Crear1;
    private javax.swing.JButton bt_Crear_A;
    private javax.swing.JButton bt_Crear_U;
    private javax.swing.JButton bt_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_Artista;
    private javax.swing.JDialog jd_Creacion;
    private com.toedter.calendar.JDateChooser jd_Creacion_Al;
    private com.toedter.calendar.JDateChooser jd_Creacion_C;
    private com.toedter.calendar.JDateChooser jd_Nacimiento;
    private javax.swing.JDialog jd_Usuario;
    private javax.swing.JLabel jl_Albumes;
    private javax.swing.JLabel jl_Canciones;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Duracion;
    private javax.swing.JLabel jl_Login;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JLabel jl_Titulo2;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JLabel jl_Usuario1;
    private javax.swing.JTree jt_Albumes;
    private javax.swing.JPasswordField pf_Contraseña;
    private javax.swing.JPasswordField pf_Contraseña1;
    private javax.swing.JRadioButton rb_Artista;
    private javax.swing.JRadioButton rb_Usuario;
    private javax.swing.JTextField tf_Agregar_AL1;
    private javax.swing.JTextField tf_Album;
    private javax.swing.JTextField tf_Apellido;
    private javax.swing.JTextField tf_Cancion;
    private javax.swing.JTextField tf_Duracion;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JTextField tf_Usuario1;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Persona> persona = new ArrayList();
    private Usuario u;
    private Artista a;
    private Cancion c;
    private Playlist pl;
    private Album al;
}
